// <auto-generated />
using System;
using GerenciadorUsuario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorUsuario.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250414175337_CriandoDBesuasTabelas")]
    partial class CriandoDBesuasTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorUsuario.Models.PapelUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomePapelUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PapelUsuario");
                });

            modelBuilder.Entity("GerenciadorUsuario.Models.StatusUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeStatusUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusUsuario");
                });

            modelBuilder.Entity("GerenciadorUsuario.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdPapelUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdStatusUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PapelUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PapelUsuarioId");

                    b.HasIndex("StatusUsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("GerenciadorUsuario.Models.Usuario", b =>
                {
                    b.HasOne("GerenciadorUsuario.Models.PapelUsuario", "PapelUsuario")
                        .WithMany()
                        .HasForeignKey("PapelUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorUsuario.Models.StatusUsuario", "StatusUsuario")
                        .WithMany()
                        .HasForeignKey("StatusUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PapelUsuario");

                    b.Navigation("StatusUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
